<!DOCTYPE html>
<html>
    <head>
        <title>YYF-YUNYIN YAF FRAMEWORK</title>
        <style type="text/css">
        body,button,a{text-align: center;color: rgb(255,255,255);background: rgb(26,188,156);}
        </style>
    </head>
    <body>
        <h1>YYF<small><sub>v<?php echo $version?></sub></small></h1>
        <h2>高效，安全，简单，优雅 <small>的框架</small></h2>
        <br/><hr/><br/>
        <form action="<?php echo $url?>/index/test" method='post'>
            <h3>POST /index/test 测试</h3>
            <input name="data" placeholder='data' type="text"/><button>POST</button>
        </form>
        <form action="<?php echo $url?>/index/test" method='get'>
            <h3>GET /index/test 测试</h3>
            <input name="data" placeholder='data' type="text"/><button>GET</button>
        </form>
            <h3>id参数绑定<a href="<?php echo $url?>/index/123">/index/123测试</a></h3>
        <br/><hr/><br/>
    <footer><small><a href="https://github.com/YunYinORG/YYF/">view YYF on Github</a></small></footer>
</body>
</html>